Feature3
MkBear13/REposit pull request #5
Opened 2019-04-21 08:59 UTC by MkBear13

2019-04-22 09:22 UTC, MaksimLion requested changes

2019-04-22 09:22 UTC, MaksimLion commented on 3func.py
> +    else:
extra block else

2019-04-22 09:22 UTC, MaksimLion commented on 3func.py
> +def slovar(list1,list2,dictor={}):
spaces after comma, read PEP8

2019-04-22 14:26 UTC, MaksimLion approved these changes

2019-04-24 10:25 UTC, AlehSivakou approved these changes

2019-04-24 10:26 UTC, AlehSivakou commented on 3func.py
> +def slovar(first_list, second_list, dictor={}):
Generally function names with verb so that it identifies what it does. for example, update, calculate_something etc.

2019-04-24 10:27 UTC, AlehSivakou approved these changes

2019-05-05 10:43 UTC, merged